bind-addr: 'localhost:7070'
secret: "oiltiwypuz0ii2b0sdmfc2n63qzawgkw"
mongodb:
  address: 'mongodb://vmware.webinstant.online:27017'
  db: evildoer
  user: root
  pass: example
metadata:
  name: cluster
  namespace: test-ns